--- #YAML:1.0
name: XML-Entities
abstract: Mapping of XML entities to Unicode
version: 0.0307
author:
    - Oldrich Kruza <sixtease@cpan.org>
license: perl
distribution_type: module
requires:
    Carp: 0
    File::Basename: 0
    LWP::UserAgent: 0
    Fatal: 0
    perl: 5.008
recommends:
    HTML::Parser: 0
build_requires:
    Test::More: 0
